<a href="https://colab.research.google.com/github/saadmarwan16/numpy_stack/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
L = [1, 2, 3]

In [ ]:
A = np.array([1, 2, 3])

In [ ]:
for e in L:
    print(e)

1
2
3


In [ ]:
for e in A: 
    print(e)

1
2
3


In [ ]:
L.append(4)
L

[1, 2, 3, 4]

In [ ]:
L + [5]

[1, 2, 3, 4, 5]

In [ ]:
A + np.array([4])

array([5, 6, 7])

In [ ]:
A + np.array([4, 5, 6])

array([5, 7, 9])

In [ ]:
2 * A

array([2, 4, 6])

In [ ]:
A + A

array([2, 4, 6])

In [ ]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
A ** 2

array([1, 4, 9])

In [ ]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [ ]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])

In [ ]:
dot = 0
for i, j in zip(a, b):
    dot += i * j

dot

11

In [ ]:
dot = 0
for i in range(len(a)):
    dot += a[i] * b[i]

dot

11

In [ ]:
np.sum(a)

3

In [ ]:
a.sum()

3

In [ ]:
a * b

array([3, 8])

In [ ]:
np.sum(a * b)

11

In [ ]:
(a * b).sum()

11

In [ ]:
np.dot(a, b)

11

In [ ]:
a.dot(b)

11

In [ ]:
a @ b

11

In [ ]:
amag = np.sqrt((a * a).sum())
amag

2.23606797749979

In [ ]:
amag = np.sqrt(a.dot(a))
amag

2.23606797749979

In [ ]:
np.linalg.norm(a)

2.23606797749979

In [ ]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))
cosangle

0.9838699100999074

In [ ]:
angle = np.arccos(cosangle)
angle

0.17985349979247847

In [ ]:
amat = np.array([[1, 2], [3, 4]])
amat

array([[1, 2],
       [3, 4]])

In [ ]:
amat[0][1]

2

In [ ]:
amat[0, 1]

2

In [ ]:
amat[:, 0]

array([1, 3])

In [ ]:
amat.T

array([[1, 3],
       [2, 4]])

In [ ]:
np.exp(amat)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
bmat = np.array([[1, 2, 3], [4, 5, 6]])
bmat

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
amat.dot(bmat)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [ ]:
np.linalg.det(amat)

-2.0000000000000004

In [ ]:
np.linalg.inv(amat)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
np.linalg.inv(amat).dot(amat)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [ ]:
np.trace(amat)

5

In [ ]:
np.diag(amat)

array([1, 4])

In [ ]:
np.diag([1, 4])

array([[1, 0],
       [0, 4]])

In [ ]:
np.trace(np.diag([1, 4]))

5

In [ ]:
# np.linalg.eigh() used to find the eighen values and eighen vectors
# np.allclose() used to correct floating point inprecision

In [ ]:
# x = np.linalg.solve(a, b)   yes
# x = np.linalg.inv(a).dot(b)     no

In [ ]:
# x1 + x2 = 2200
# 1.5x1 + 4x2 = 5050

a = np.array([[1, 1], [1.5, 4]])
b = np.array([2200, 5050])
np.linalg.solve(a, b)

array([1500.,  700.])

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# n * np.ones((2, 3))   where (2, 3) can be any tuple of any dimension

10 * np.ones((2, 3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [ ]:
# identity matrix. The determinant of any identity matrix is 1.0
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.random()

0.7380816930735945

In [ ]:
np.random.random((2, 3))

array([[0.77449588, 0.23575552, 0.02436573],
       [0.69174482, 0.57390012, 0.09573539]])

In [ ]:
np.random.randn(2, 3)

array([[-1.31926052,  1.69814716,  1.19133216],
       [-1.07127912,  0.34549225, -0.94804488]])

In [ ]:
norm_dist = np.random.randn(100000)
np.mean(norm_dist)

-0.0005647759629397011

In [ ]:
np.var(norm_dist)

1.0069184421162702

In [ ]:
np.std(norm_dist)

1.0034532585607914

In [ ]:
mat_dist = np.random.randn(10000, 3)
mat_dist

array([[ 0.80444916,  0.46492749, -0.47969907],
       [-1.08704719, -0.92429472, -1.46422942],
       [-0.37111275, -2.23087459, -0.82002328],
       ...,
       [-0.01105841, -0.68435248,  0.22748967],
       [ 0.61189758, -0.94711836,  0.03789982],
       [-1.35113101,  0.50933158,  0.77735054]])

In [ ]:
np.mean(mat_dist)

0.001121815456641095

In [ ]:
np.mean(mat_dist, axis=0)

array([-0.00221907,  0.0016133 ,  0.00397122])

In [ ]:
np.mean(mat_dist, axis=1)

array([ 0.12970504, -0.15949173,  0.96098031, ..., -0.48906558,
        0.6850114 ,  0.05548463])

In [ ]:
np.mean(mat_dist, axis=1).shape

(100000,)

In [ ]:
np.cov(mat_dist)

array([[ 0.44277183,  0.15652276, -0.02080508, ..., -0.15651391,
         0.0559906 , -0.60302184],
       [ 0.15652276,  0.07671405, -0.14918789, ..., -0.11531527,
        -0.09484624, -0.10745721],
       [-0.02080508, -0.14918789,  0.94178937, ...,  0.40525893,
         0.7577977 , -0.6728967 ],
       ...,
       [-0.15651391, -0.11531527,  0.40525893, ...,  0.22361437,
         0.30182187, -0.08341705],
       [ 0.0559906 , -0.09484624,  0.7577977 , ...,  0.30182187,
         0.62171082, -0.64303849],
       [-0.60302184, -0.10745721, -0.6728967 , ..., -0.08341705,
        -0.64303849,  1.34393149]])

In [ ]:
np.cov(mat_dist).shape

(10000, 10000)

In [ ]:
np.cov(mat_dist.T)

array([[ 0.99004157,  0.00410235,  0.00302303],
       [ 0.00410235,  0.99177185, -0.00799463],
       [ 0.00302303, -0.00799463,  0.98101272]])

In [ ]:
np.cov(mat_dist, rowvar=False)

array([[ 0.99004157,  0.00410235,  0.00302303],
       [ 0.00410235,  0.99177185, -0.00799463],
       [ 0.00302303, -0.00799463,  0.98101272]])

In [ ]:
np.random.randint(0, 10, size=(3, 3,))

array([[3, 3, 1],
       [8, 2, 5],
       [4, 7, 6]])

In [ ]:
np.random.choice(10, size=(10000, ))    # or np.random.choice(10, size=10000, )

array([4, 1, 7, ..., 5, 2, 8])

In [ ]:
np.random.choice(10, size=(3, 3))

array([[2, 8, 9],
       [4, 7, 8],
       [3, 2, 4]])